---

- name: Check installed and desired consul versions
  include_tasks: check.yml
  when: consul_install

- name: Install consul
  include_tasks: install.yml
  when:
    - consul_install
    - consul_installed_version != consul_install_version

- name: Configure consul
  include_tasks: configure.yml
  when: consul_configure

- name: Configure consul agent service
  include_tasks: service.yml
